jest.mock('@mccsoft/react-native-matomo', () => ({
  MatomoTracker: jest.fn().mockImplementation(() => ({
    initialize: jest.fn().mockResolvedValue(undefined),
    initializeWithOptions: jest.fn().mockResolvedValue(undefined),
    isInitialized: jest.fn().mockResolvedValue(true),
    getInstanceId: jest.fn().mockReturnValue('default'),
    trackView: jest.fn().mockResolvedValue(undefined),
    trackEvent: jest.fn().mockResolvedValue(undefined),
    trackGoal: jest.fn().mockResolvedValue(undefined),
    trackAppDownload: jest.fn().mockResolvedValue(undefined),
    trackSiteSearch: jest.fn().mockResolvedValue(undefined),
    setCustomDimension: jest.fn().mockResolvedValue(undefined),
    setUserId: jest.fn().mockResolvedValue(undefined),
    setAppOptOut: jest.fn().mockResolvedValue(undefined),
    isOptOut: jest.fn().mockResolvedValue(false),
    dispatch: jest.fn().mockResolvedValue(undefined),
    setDispatchInterval: jest.fn().mockResolvedValue(undefined),
    getDispatchInterval: jest.fn().mockResolvedValue(30),
    reset: jest.fn().mockResolvedValue(undefined),
    resetCustomDimensions: jest.fn().mockResolvedValue(undefined),
    stop: jest.fn().mockResolvedValue(undefined),
    getUserId: jest.fn().mockResolvedValue(null),
    startNewSession: jest.fn().mockResolvedValue(undefined),
  })),
  // Legacy API mocks
  initialize: jest.fn().mockResolvedValue(undefined),
  isInitialized: jest.fn().mockResolvedValue(true),
  trackView: jest.fn().mockResolvedValue(undefined),
  trackEvent: jest.fn().mockResolvedValue(undefined),
  trackGoal: jest.fn().mockResolvedValue(undefined),
  trackAppDownload: jest.fn().mockResolvedValue(undefined),
  trackSiteSearch: jest.fn().mockResolvedValue(undefined),
  setCustomDimension: jest.fn().mockResolvedValue(undefined),
  setUserId: jest.fn().mockResolvedValue(undefined),
  setAppOptOut: jest.fn().mockResolvedValue(undefined),
  isOptOut: jest.fn().mockResolvedValue(false),
  dispatch: jest.fn().mockResolvedValue(undefined),
  setDispatchInterval: jest.fn().mockResolvedValue(undefined),
  getDispatchInterval: jest.fn().mockResolvedValue(30),
  reset: jest.fn().mockResolvedValue(undefined),
  resetCustomDimensions: jest.fn().mockResolvedValue(undefined),
  stop: jest.fn().mockResolvedValue(undefined),
  getUserId: jest.fn().mockResolvedValue(null),
  startNewSession: jest.fn().mockResolvedValue(undefined),
}));
