const mockTracker = {
  initialize: jest.fn(),
  initializeWithOptions: jest.fn(),
  isInitialized: jest.fn(),
  trackView: jest.fn(),
  trackEvent: jest.fn(),
  trackGoal: jest.fn(),
  trackAppDownload: jest.fn(),
  setCustomDimension: jest.fn(),
  setUserId: jest.fn(),
  setAppOptOut: jest.fn(),
  isOptOut: jest.fn(),
  dispatch: jest.fn(),
  setDispatchInterval: jest.fn(),
  getDispatchInterval: jest.fn(),
  trackSiteSearch: jest.fn(),
  stop: jest.fn(),
  reset: jest.fn(),
  resetCustomDimensions: jest.fn(),
  getUserId: jest.fn(),
  startNewSession: jest.fn(),
  getInstanceId: jest.fn().mockReturnValue('default'),
};

jest.mock('@mccsoft/react-native-matomo', () => ({
  MatomoTracker: jest.fn().mockImplementation(() => mockTracker),
  Matomo: jest.fn().mockImplementation(() => mockTracker),
  initialize: jest.fn(),
  isInitialized: jest.fn(),
  trackView: jest.fn(),
  trackEvent: jest.fn(),
  trackGoal: jest.fn(),
  trackAppDownload: jest.fn(),
  setCustomDimension: jest.fn(),
  setUserId: jest.fn(),
  setAppOptOut: jest.fn(),
  isOptOut: jest.fn(),
  dispatch: jest.fn(),
  setDispatchInterval: jest.fn(),
  getDispatchInterval: jest.fn(),
  trackSiteSearch: jest.fn(),
  stop: jest.fn(),
  reset: jest.fn(),
  resetCustomDimensions: jest.fn(),
  getUserId: jest.fn(),
  startNewSession: jest.fn(),
}));
